# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.

trigger:
- main

pool:
  name: 'Default'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  projectPath: 'Tailspin.SpaceGame.Web/Tailspin.SpaceGame.Web.csproj'

steps:
- task: UseDotNet@2
  displayName: 'Use .NET Core SDK'
  inputs:
    packageType: 'sdk'
    version: '8.0.x'

- script: dotnet restore 
  displayName: 'Restore NuGet packages'

- script: dotnet build  --configuration $(buildConfiguration)
  displayName: 'Build the solution'

- script: dotnet test  --configuration $(buildConfiguration) --no-build
  displayName: 'Run tests'

- script: dotnet publish $(projectPath) --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)
  displayName: 'Publish the application'

- task: PublishBuildArtifacts@1
  displayName: 'Publish artifacts'
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'drop'